# Permalinks
#
permalink:           pretty

# Setup
title:               BlueMatt's Blog
tagline:             On Building a Bitcoin for Everyone
description:         "A Blog on Bitcoin's ethos, its values and what I see in it. All opinions are my own, though I try to ensure others don't completely disagree."
url:                 http://bluematt.bitcoin.ninja
paginate:            2
baseurl:             ''

gems:
  - jekyll-redirect-from

# About/contact
author:
  name:              Matt Corallo
  url:               https://twitter.com/TheBlueMatt
  email:             bluematt@bitcoin.ninja

# Custom vars
version:             1.0.0
